exports.ROLE = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
  STAFF: "STAFF",
};
exports.CATEGORY_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};
exports.SKIN_TYPE = {
  OILY: "OILY",
  DRY: "DRY",
  COMBINATION: "COMBINATION",
  SENSITIVE: "SENSITIVE",
  NORMAL: "NORMAL",
};
exports.IMAGE_TYPE = {
  PRODUCT: "PRODUCT",
  QUIZ: "QUIZ",
  BRAND: "BRAND",
  CATEGORY: "CATEGORY",
  PRDUCT_VARIATION: "PRODUCT_VARIATION",
};
